import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ReduxProvider from "@/redux/ReduxProvider";

const redHatText = localFont({
  src: [
    { path: "./fonts/RedHatText-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/RedHatText-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/RedHatText-SemiBold.ttf", weight: "600", style: "normal" },
  ],
  variable: "--font-red-hat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} antialiased`}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
